#!/usr/bin/env python3
"""Render season-board.json into design/prototype.html as the LAN leaderboard.

The section is a data block + a renderer, not a static table, because it now
carries the day boards' interaction model — sortable headers, position/team/
style filter chips, medals that follow the current sort and filter. Same
classes, same behaviour, so the two boards read as one system. Like the day
boards, it renders nothing if scripting fails. Idempotent — the section lives
between two markers and is replaced wholesale on each run.

Display names come from the page's own #player-names block (settled in
build_ballots.py), so this board, the day boards and the awards all answer to
one naming rule. The full in-game name stays on each cell's title.

The renderer <script> is extracted into assets/site.js by build_site.py and so
ships to every edition page — it exits early where the board's elements are
absent. The #lanboard-data block only reaches the 2026 page because build_site
routes data blocks by its OWNED table; adding a new block id here means adding
it there too.

    python inject_season_board.py           # rewrite the section
    python inject_season_board.py --check   # exit 1 if the page is stale
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BOARD = os.path.join(HERE, "season-board.json")
PAGE = os.path.normpath(os.path.join(HERE, "..", "design", "prototype.html"))

START = "<!-- season-board:start (generated by lan-stats/inject_season_board.py) -->"
END = "<!-- season-board:end -->"
ANCHOR = '<section id="awards" data-ed="philly-2026">'

# Final-standings order, same pairs as buildStatsBoard's TEAMS default in the
# page script — the chip row must name teams the way the day boards' does.
TEAMS = [
    ["North Atlantic Treaty Org", "NATO"],
    ["icyHOT", "icyHOT"],
    ["dicE", "dicE"],
    ["Arrested Development", "BLUTH"],
    ["onLAN thunder", "FJTM"],
    ["Best Buds", "[bb]"],
    ["NoSoul", "NoSoul"],
    ["Price is Right", "[$]"],
    ["b Team", "b Team"],
    ["Uncle Rico's Time Machine", "uR[TM]"],
]

# The renderer. Plain ES5 like the rest of the page; guarded because
# build_site.py ships it to every edition. The sorting/medal model is the day
# boards' verbatim: rank and medals recompute against the last numeric column
# sorted (state.rankKey), within whatever filter is active.
SCRIPT = """(function () {
  "use strict";
  var dataEl = document.getElementById("lanboard-data");
  var elTable = document.getElementById("lb-table");
  if (!dataEl || !elTable) return;   // not this edition's page
  var DATA = JSON.parse(dataEl.textContent);
  var PLAYERS = DATA.players;
  var TEAMS = DATA.teams;
  var TEAM_TAG = {};
  TEAMS.forEach(function (t) { TEAM_TAG[t[0]] = t[1]; });
  var ROLE_ORDER = ["Rifle", "Heavy", "3rd", "Sniper"];
  var TIER_ORDER = ["Ace", "Veteran", "Regular", "Recruit"];
  var ARCH_ORDER = ["Sharpshooter", "Fragger", "Flagger", "Support",
                    "All-rounder", "Generalist"];
  var elRole = document.getElementById("lb-rolechips");
  var elTeam = document.getElementById("lb-teamchips");
  var elStyle = document.getElementById("lb-stylechips");
  var elHead = document.getElementById("lb-head");
  var state = { role: null, team: null, arch: null,
                sortKey: "ktpr", sortDir: "desc", rankKey: "ktpr" };
  var fmt = function (n) { return n.toLocaleString("en-US"); };

  function el(tag, cls, text) {
    var e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text !== undefined) e.textContent = text;
    return e;
  }

  function chip(label, pressed, onClick) {
    var b = el("button", "chip", label);
    b.setAttribute("aria-pressed", String(pressed));
    b.addEventListener("click", onClick);
    return b;
  }

  var COLS = [
    { key: "rank",  label: "#",            type: "rank" },
    { key: "player", label: "Player",      type: "alpha" },
    { key: "pos",   label: "Pos",          type: "role" },
    { key: "ktpr",  label: "KTPR",         type: "num" },
    { key: "style", label: "Style",        type: "style", tip: true },
    { key: "kd",    label: "K/D",          type: "num" },
    { key: "kph",   label: "Kills/half",   type: "num" },
    { key: "fph",   label: "Flags/half",   type: "num" },
    { key: "aph",   label: "Assists/half", type: "num", hud: true },
    { key: "dph",   label: "Damage/half",  type: "num" },
    { key: "bph",   label: "Breaks/half",  type: "num", hud: true },
    { key: "m",     label: "Matches",      type: "num" }
  ];

  function byNumDesc(key) {
    return function (a, b) {
      if (b[key] !== a[key]) return b[key] - a[key];
      if (b.ktpr !== a.ktpr) return b.ktpr - a.ktpr;
      return a.dn.localeCompare(b.dn);
    };
  }
  function styleOrd(r) {
    return TIER_ORDER.indexOf(r.tier) * 10 + ARCH_ORDER.indexOf(r.arch);
  }
  // standings under the current ranking metric, independent of display order —
  // reversing a sort must not move the medals
  function standings(rows) {
    var order = rows.slice().sort(byNumDesc(state.rankKey));
    var pos = new Map();
    order.forEach(function (r, i) { pos.set(r, i); });
    return pos;
  }
  function sortRows(rows) {
    var out = rows.slice();
    var key = state.sortKey;
    if (key === "player") {
      out.sort(function (a, b) { return a.dn.localeCompare(b.dn); });
    } else if (key === "pos") {
      out.sort(function (a, b) {
        var d = ROLE_ORDER.indexOf(a.pos) - ROLE_ORDER.indexOf(b.pos);
        return d !== 0 ? d : b.ktpr - a.ktpr;
      });
    } else if (key === "style") {
      out.sort(function (a, b) {
        var d = styleOrd(a) - styleOrd(b);
        return d !== 0 ? d : b.ktpr - a.ktpr;
      });
    } else if (key === "rank") {
      out.sort(byNumDesc(state.rankKey));
    } else {
      out.sort(byNumDesc(key));
    }
    var canonicalIsAsc = (key === "player" || key === "pos" ||
                          key === "style" || key === "rank");
    if (canonicalIsAsc ? state.sortDir === "desc" : state.sortDir === "asc") out.reverse();
    return out;
  }
  function clickSort(col) {
    var firstDir = { num: "desc", alpha: "asc", role: "asc", style: "asc", rank: "asc" };
    if (state.sortKey === col.key) {
      state.sortDir = state.sortDir === "desc" ? "asc" : "desc";
    } else {
      state.sortKey = col.key;
      state.sortDir = firstDir[col.type];
      if (col.type === "num") state.rankKey = col.key;
    }
    render();
  }

  // ---- Style tooltip (hover + keyboard focus on the column header) ----
  // The label's meaning, straight from ktpr_engine.py's classify_styles.
  var tip = el("div", "tooltip");
  tip.id = "style-tip";
  tip.setAttribute("role", "tooltip");
  tip.hidden = true;
  document.body.appendChild(tip);
  (function fillTip() {
    var p1 = el("p"); p1.appendChild(el("b", null, "Style — a tier and an archetype."));
    tip.appendChild(p1);
    tip.appendChild(el("p", null,
      "The tier is where the player's KTPR ranks on this board: Ace is the top " +
      "15%, Veteran to 40%, Regular to 70%, Recruit the rest."));
    tip.appendChild(el("p", null,
      "The archetype is the shape of the profile, not its quality — three axes, " +
      "each measured against the field median: fragging (half K/D, half kills), " +
      "objective (70% flags, 30% capture breaks), support (60% assists, 40% damage)."));
    tip.appendChild(el("p", null,
      "Strong on two or more axes (1.12× the median or better) makes an " +
      "All-rounder; no axis ahead of the next by at least 0.12 makes a " +
      "Generalist. A fragging-led profile is a Sharpshooter when K/D leads " +
      "kill volume by 0.30 or more, otherwise a Fragger; objective-led is a " +
      "Flagger, support-led is Support."));
  })();
  function showTip(anchor) {
    tip.hidden = false;
    var r = anchor.getBoundingClientRect();
    var w = Math.min(360, window.innerWidth - 24);
    tip.style.maxWidth = w + "px";
    tip.style.left = Math.max(12, Math.min(r.left, window.innerWidth - w - 12)) + "px";
    var top = r.bottom + 8;
    if (top + tip.offsetHeight > window.innerHeight - 8) top = Math.max(8, r.top - tip.offsetHeight - 8);
    tip.style.top = top + "px";
  }
  function hideTip() { tip.hidden = true; }
  window.addEventListener("scroll", hideTip, true);
  document.addEventListener("keydown", function (e) { if (e.key === "Escape") hideTip(); });

  function filtered() {
    return PLAYERS.filter(function (r) {
      if (state.role !== null && r.pos !== state.role) return false;
      if (state.team !== null && r.tm !== state.team) return false;
      if (state.arch !== null && r.arch !== state.arch) return false;
      return true;
    });
  }

  // Each chip row's counts respect the OTHER filters, so the numbers always
  // describe what clicking would actually show.
  function counts(skip) {
    var c = {};
    PLAYERS.forEach(function (r) {
      if (skip !== "role" && state.role !== null && r.pos !== state.role) return;
      if (skip !== "team" && state.team !== null && r.tm !== state.team) return;
      if (skip !== "arch" && state.arch !== null && r.arch !== state.arch) return;
      var k = skip === "role" ? r.pos : skip === "team" ? r.tm : r.arch;
      c[k] = (c[k] || 0) + 1;
    });
    return c;
  }
  function renderRoleChips() {
    elRole.textContent = "";
    var c = counts("role");
    elRole.appendChild(chip("All positions", state.role === null, function () {
      state.role = null; render();
    }));
    ROLE_ORDER.forEach(function (role) {
      elRole.appendChild(chip(role + " · " + (c[role] || 0), state.role === role, function () {
        state.role = state.role === role ? null : role; render();
      }));
    });
  }
  function renderTeamChips() {
    elTeam.textContent = "";
    var c = counts("team");
    elTeam.appendChild(chip("All teams", state.team === null, function () {
      state.team = null; render();
    }));
    TEAMS.forEach(function (t) {
      var b = chip(t[1] + " · " + (c[t[0]] || 0), state.team === t[0], function () {
        state.team = state.team === t[0] ? null : t[0]; render();
      });
      b.title = t[0];
      elTeam.appendChild(b);
    });
  }
  function renderStyleChips() {
    elStyle.textContent = "";
    var c = counts("arch");
    elStyle.appendChild(chip("All styles", state.arch === null, function () {
      state.arch = null; render();
    }));
    ARCH_ORDER.forEach(function (arch) {
      elStyle.appendChild(chip(arch + " · " + (c[arch] || 0), state.arch === arch, function () {
        state.arch = state.arch === arch ? null : arch; render();
      }));
    });
  }

  function rolePill(row) {
    var p = el("span", "rolepill" + (row.rs === "inferred" ? " inferred" : ""), row.pos);
    p.title = row.rs === "inferred"
      ? "Position read from class play — unchallenged in the staff pass"
      : "Position named by staff";
    return p;
  }
  function ktprCell(v, max) {
    var wrap = el("div", "ktprcell");
    wrap.appendChild(el("b", null, v.toFixed(3)));
    var bar = el("div", "ktprbar");
    var i = el("i");
    i.style.width = Math.max(4, Math.round(v / max * 100)) + "%";
    bar.appendChild(i);
    wrap.appendChild(bar);
    return wrap;
  }

  function render() {
    renderRoleChips();
    renderTeamChips();
    renderStyleChips();
    hideTip();

    var rows = filtered();
    var isFiltered = state.role !== null || state.team !== null || state.arch !== null;
    elHead.textContent = isFiltered
      ? [state.team !== null ? (TEAM_TAG[state.team] || state.team) : null,
         state.role !== null ? state.role : null,
         state.arch !== null ? state.arch : null]
          .filter(Boolean).join(" · ") + " — ranked within this view"
      : "All " + PLAYERS.length + " players · both days combined";

    elTable.textContent = "";
    var thead = el("thead");
    var htr = el("tr");
    COLS.forEach(function (col) {
      var th = el("th", col.type === "num" ? "r" : null);
      var btn = el("button", "sortbtn");
      btn.appendChild(el("span", col.tip ? "tipcue" : null, col.label));
      if (col.hud) btn.appendChild(el("span", "srcbadge", "HUD"));
      if (state.sortKey === col.key) {
        th.setAttribute("aria-sort", state.sortDir === "desc" ? "descending" : "ascending");
        btn.appendChild(el("span", "dir", state.sortDir === "desc" ? "▼" : "▲"));
      }
      var what = { rank: "rank", alpha: "player name", role: "position", style: "style" }[col.type] || col.label;
      btn.title = "Sort by " + what;
      btn.addEventListener("click", function () { clickSort(col); });
      if (col.tip) {
        btn.setAttribute("aria-describedby", "style-tip");
        btn.addEventListener("mouseenter", function () { showTip(btn); });
        btn.addEventListener("mouseleave", hideTip);
        btn.addEventListener("focus", function () { showTip(btn); });
        btn.addEventListener("blur", hideTip);
      }
      th.appendChild(btn);
      htr.appendChild(th);
    });
    thead.appendChild(htr);
    elTable.appendChild(thead);

    var tbody = el("tbody");
    var pos = standings(rows);
    var sorted = sortRows(rows);
    var maxK = sorted.reduce(function (m, r) { return Math.max(m, r.ktpr); }, 0.001);

    if (!sorted.length) {
      var trE = el("tr");
      var tdE = el("td", null, "No players in this view.");
      tdE.colSpan = COLS.length;
      trE.appendChild(tdE);
      tbody.appendChild(trE);
    }

    sorted.forEach(function (row) {
      var st = pos.get(row);
      var medal = st === 0 ? "m1" : st === 1 ? "m2" : st === 2 ? "m3"
        : (st === 3 || st === 4) ? "m45" : null;
      var tr = el("tr", medal);
      tr.appendChild(el("td", "rank", String(st + 1)));
      var tdp = el("td", "player", row.dn); tdp.title = row.n;
      tr.appendChild(tdp);
      var tdr = el("td"); tdr.appendChild(rolePill(row)); tr.appendChild(tdr);
      var tdk = el("td"); tdk.appendChild(ktprCell(row.ktpr, maxK)); tr.appendChild(tdk);
      tr.appendChild(el("td", null, row.tier + " " + row.arch));
      tr.appendChild(el("td", "r", row.kd.toFixed(2)));
      tr.appendChild(el("td", "r", row.kph.toFixed(1)));
      tr.appendChild(el("td", "r", row.fph.toFixed(2)));
      tr.appendChild(el("td", "r", row.aph.toFixed(1)));
      tr.appendChild(el("td", "r", fmt(Math.round(row.dph))));
      tr.appendChild(el("td", "r", row.bph.toFixed(2)));
      tr.appendChild(el("td", "r", String(row.m)));
      tbody.appendChild(tr);
    });
    elTable.appendChild(tbody);
  }

  render();
})();"""


def page_names(page: str) -> dict:
    """The settled display names, read from the page's #player-names block.

    build_ballots.py derives them (team-prefix strip + flair trim + one-off
    untag) and embeds the answer; reading it back here keeps this board on the
    same rule without a second implementation.
    """
    m = re.search(r'<script id="player-names" type="application/json">(.*?)</script>',
                  page, re.S)
    return json.loads(m.group(1)) if m else {}


def payload(board: dict, names: dict) -> str:
    players = []
    for r in board["players"]:
        tier, arch = r["style"].split(" ", 1)
        players.append({
            "n": r["name"], "dn": names.get(r["name"], r["name"]),
            "tm": r["team"], "pos": r["position"],
            "rs": r.get("role_source", "inferred"),
            "tier": tier, "arch": arch,
            "ktpr": r["ktpr"], "kd": r["kd"],
            "kph": r["kills_per_half"], "fph": r["flags_per_half"],
            "aph": r["assists_per_half"], "dph": r["damage_per_half"],
            "bph": r["breaks_per_half"], "m": r["matches"], "h": r["halves"],
        })
    data = {"teams": TEAMS, "players": players}
    # "</" would end the script block early if a name ever carries it
    return json.dumps(data, ensure_ascii=False,
                      separators=(",", ":")).replace("</", "<\\/")


def render(board: dict, names: dict) -> str:
    k = board["knobs"]
    n = len(board["players"])
    return f"""{START}
  <section id="leaderboard" data-ed="philly-2026">
    <div class="sec-head"><h2>Philly LAN 2026 Leaderboard</h2>
      <span class="meta">both days combined &middot; the current KTPR formula</span></div>

    <div class="note-box">
      <b>A different rating to the two boards above.</b> Those score kills, K/D and
      flags against the field of a single day. This one runs the formula KTPR
      actually uses now &mdash; six contributions (kill volume, kill efficiency,
      assists, damage, flags, capture breaks) weighted into one number, each
      measured against the median of a player&rsquo;s own position rather than the
      whole field. <b>1.00 is an average player.</b> It reads the whole weekend at
      once, so unlike the day boards these numbers do compare across Saturday and
      Sunday.
    </div>

    <div class="note-box">
      <b>Two of the six rating inputs are HUD-sourced.</b> Assists and capture
      breaks exist only in the broadcast HUD <span class="srcbadge">HUD</span>,
      which saved on a timer while the server was up rather than only during live
      play &mdash; so warmup can leak into those two inputs, and they carry the
      badge below. The other four &mdash; kill volume, kill efficiency, damage and
      flags &mdash; come from the match record and count match time only. The fix
      is to teach the match record to log assists and breaks itself; until then
      this is the honest label.
    </div>

    <div class="note-box">
      <b>Team finish is deliberately not in here.</b> The live formula can multiply
      each player by where their company finished. That is switched off for this
      board &mdash; it would fold the result of the weekend into a number presented
      as individual performance, and the awards this feeds are judged per stage.
    </div>

    <div class="filters">
      <div class="chipgroup" role="group" aria-label="Filter by position">
        <span class="chiplabel" aria-hidden="true">Position</span>
        <span class="chipslot" id="lb-rolechips"></span>
      </div>
      <div class="chipgroup" role="group" aria-label="Filter by team">
        <span class="chiplabel" aria-hidden="true">Team</span>
        <span class="chipslot" id="lb-teamchips"></span>
      </div>
      <div class="chipgroup" role="group" aria-label="Filter by style">
        <span class="chiplabel" aria-hidden="true">Style</span>
        <span class="chipslot" id="lb-stylechips"></span>
      </div>
    </div>

    <div class="panel">
      <div class="head" id="lb-head">All {n} players &middot; both days combined</div>
      <div class="body scrollbox">
        <table class="leader" id="lb-table"></table>
      </div>
    </div>

    <p class="status-foot"><b>Positions</b> are the league's four &mdash; dashed
      pill = read from class play; solid = named by staff. Click any column header
      to sort; rank, and the medal colours with it, recompute within whatever
      filter and sort you're looking at. Hover <b>Style</b> for what the labels
      mean. Clan tags are stripped for display &mdash; the full in-game name is on
      each player cell's title.</p>
    <p class="status-foot"><b>Weights</b> kill_exp {k["kill_exp"]} &middot;
      kills {k["tw_kill"]} &middot; K/D {k["tw_kd"]} &middot; assists {k["tw_assist"]} &middot;
      damage {k["tw_damage"]} &middot; flags {k["tw_flag"]} &middot; breaks {k["tw_break"]}
      &middot; break smoothing {k["break_smooth_k"]}. Generated from the published
      stats by <b>build_season_board.py</b>, so the board and the numbers behind it
      cannot disagree.</p>
    <script id="lanboard-data" type="application/json">{payload(board, names)}</script>
    <script>
{SCRIPT}
    </script>
  </section>
{END}
"""


def main() -> int:
    board = json.load(open(BOARD, encoding="utf-8"))
    page = open(PAGE, encoding="utf-8").read()
    section = render(board, page_names(page))

    if START in page:
        # lambda replacement: the section carries backslashes and "\\g"-like
        # text a plain re.sub replacement string would mangle
        new = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?",
                     lambda m: section, page, flags=re.S)
    else:
        if ANCHOR not in page:
            print(f"anchor not found in {PAGE}: {ANCHOR}")
            return 2
        new = page.replace(ANCHOR, section + "\n  " + ANCHOR, 1)

    if "--check" in sys.argv:
        if new != page:
            print("prototype.html season board is STALE — re-run inject_season_board.py")
            return 1
        print("prototype.html season board is current")
        return 0

    if new == page:
        print("no change")
        return 0
    with open(PAGE, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    print(f"injected LAN leaderboard ({len(board['players'])} rows) into {PAGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
