#!/usr/bin/env python3
"""Render season-board.json into design/prototype.html as the unified stats board.

One grid, three views: Saturday, Sunday and the full weekend are tabs on a
single board (section id="stats" — the nav and the publication gate both key on
that id). Every view is scored by the current team formula; the per-day views
are rated against that day's own field, the weekend view against combined
totals. This section replaced BOTH the old static day-board section and the
separate weekend leaderboard section on 2026-08-09.

The section is a data block + a renderer, not a static table. The counts and
detail payloads (hitboxes, class spawns, streak stories, prone time) come from
the page's own #lan-data block — embedded once, too big to duplicate — and the
renderer joins them with this board's ratings at load time. The weekend rows
are aggregated in the renderer from the two day rows: sums for counts, max for
the best streak, rates recomputed from summed totals over summed halves (never
an average of two days' rates). The join is BY NAME per day, which is safe only
because this script verifies at injection time that every name in the payload
exists in #lan-data and vice versa — 18 of 61 players changed names between the
days, so the weekend entries carry both day names explicitly.

Display names come from the page's own #player-names block (settled in
build_ballots.py) layered over the day boards' team-prefix derivation, so this
board and the awards answer to one naming rule. The full in-game name stays on
each cell's title.

The renderer <script> is extracted into assets/site.js by build_site.py and so
ships to every edition page — it exits early where the board's elements are
absent. The #lanboard-data block only reaches the 2026 page because build_site
routes data blocks by its OWNED table; adding a new block id here means adding
it there too.

    python inject_season_board.py           # rewrite the section
    python inject_season_board.py --check   # exit 1 if the page is stale
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BOARD = os.path.join(HERE, "season-board.json")
PAGE = os.path.normpath(os.path.join(HERE, "..", "design", "prototype.html"))

START = "<!-- season-board:start (generated by lan-stats/inject_season_board.py) -->"
END = "<!-- season-board:end -->"
ANCHOR = '<section id="awards" data-ed="philly-2026">'

DAY_KEYS = ["08-01", "08-02"]          # LD.days order in #lan-data
# Tab faces. The match counts are event facts, not derivable from lan-stats.json
# (it has no per-day match list) — same numbers the old static tabs carried.
TABS = [
    ("08-01", "Saturday &middot; Aug 1",
     "group play &middot; 31 matches &middot; rated against Saturday's field"),
    ("08-02", "Sunday &middot; Aug 2",
     "playoffs &amp; finals &middot; 27 matches &middot; rated against Sunday's field"),
    ("weekend", "Full weekend",
     "all 58 matches &middot; rated against the combined field"),
]

# Final-standings order — the chip row names teams the way the boards do.
TEAMS = [
    ["North Atlantic Treaty Org", "NATO"],
    ["icyHOT", "icyHOT"],
    ["dicE", "dicE"],
    ["Arrested Development", "BLUTH"],
    ["onLAN thunder", "FJTM"],
    ["Best Buds", "[bb]"],
    ["NoSoul", "NoSoul"],
    ["Price is Right", "[$]"],
    ["b Team", "b Team"],
    ["Uncle Rico's Time Machine", "uR[TM]"],
]

# The renderer. Plain ES5 like the rest of the page; guarded because
# build_site.py ships it to every edition. Runs after DOMContentLoaded because
# it reads #lan-data, which sits later in the document than this section.
# The sorting/medal model is the old day boards' verbatim: rank and medals
# recompute against the last numeric column sorted (state.rankKey), within
# whatever view and filter is active.
SCRIPT = """(function () {
  "use strict";
  function init() {
    var dataEl = document.getElementById("lanboard-data");
    var ldEl = document.getElementById("lan-data");
    var elTable = document.getElementById("lb-table");
    if (!dataEl || !ldEl || !elTable) return;   // not this edition's page
    var PD = JSON.parse(dataEl.textContent);
    var LD = JSON.parse(ldEl.textContent);
    var namesEl = document.getElementById("player-names");
    var GIVEN = namesEl ? JSON.parse(namesEl.textContent) : {};

    var VIEW_KEYS = ["08-01", "08-02", "weekend"];
    var ROLE_ORDER = ["Rifle", "Heavy", "3rd", "Sniper"];
    var TIER_ORDER = ["Ace", "Veteran", "Regular", "Recruit"];
    var ARCH_ORDER = ["Sharpshooter", "Fragger", "Flagger", "Support",
                      "All-rounder", "Generalist"];
    var TEAMS = PD.teams;
    var TEAM_TAG = {};
    TEAMS.forEach(function (t) { TEAM_TAG[t[0]] = t[1]; });

    var state = { view: 2, map: null, role: null, team: null, arch: null,
                  sortKey: "ktpr", sortDir: "desc", rankKey: "ktpr",
                  showAll: false };
    var fmt = function (n) { return n.toLocaleString("en-US"); };
    function possessive(s) { return s + (/s$/i.test(s) ? "'" : "'s"); }
    function el(tag, cls, text) {
      var e = document.createElement(tag);
      if (cls) e.className = cls;
      if (text !== undefined) e.textContent = text;
      return e;
    }
    // seconds as m:ss — a bare "912.4" reads as a score, not a duration
    function mmss(s) {
      if (s === null || s === undefined) return "\\u2014";
      if (s < 1) return "0:00";
      var m = Math.floor(s / 60), r = Math.round(s % 60);
      if (r === 60) { m += 1; r = 0; }
      return m + ":" + (r < 10 ? "0" : "") + r;
    }

    // ---- display names ----
    // Team-prefix derivation over every day roster (the longest common prefix
    // across a team's names IS the tag), then #player-names wins where it has
    // an opinion — the same two-layer rule the old day boards used.
    var SHORT = {};
    (function buildShortNames() {
      var byTeam = {};
      LD.days.forEach(function (d) {
        d.players.forEach(function (p) {
          if (!p.tm) return;
          (byTeam[p.tm] = byTeam[p.tm] || []).push(p.n);
        });
      });
      Object.keys(byTeam).forEach(function (team) {
        var names = byTeam[team];
        if (names.length < 2) return;
        var pre = names[0];
        names.forEach(function (n) {
          var i = 0;
          while (i < pre.length && i < n.length && pre[i] === n[i]) i++;
          pre = pre.slice(0, i);
        });
        if (pre.length < 2) return;   // a 1-char overlap is coincidence
        names.forEach(function (n) {
          var s = n.slice(pre.length).trim();
          if (s) SHORT[n] = s;
        });
      });
      Object.keys(GIVEN).forEach(function (n) { SHORT[n] = GIVEN[n]; });
    })();
    function shortName(n) { return SHORT[n] || n; }
    window.shortName = shortName;   // the awards board reuses the same rule

    // ---- row models ----
    function copyRow(r) {
      var o = {};
      Object.keys(r).forEach(function (k) { o[k] = r[k]; });
      return o;
    }
    function dayModel(di, key) {
      var rated = PD.views[key].players;
      var out = [];
      LD.days[di].players.forEach(function (r) {
        var x = rated[r.n];
        if (!x) return;   // injection-time verification makes this unreachable
        var row = copyRow(r);
        row.ktpr = x[0]; row.tier = x[1]; row.arch = x[2];
        out.push(row);
      });
      return out;
    }
    function indexBy(rows) {
      var m = {};
      rows.forEach(function (r) { m[r.n] = r; });
      return m;
    }
    var SUM = ["k", "d", "fl", "hs", "as", "dm", "cb", "pr", "pre",
               "hits", "hsh", "caps", "obj", "nk", "gk", "m", "h"];
    function weekendModel(day1, day2) {
      var by1 = indexBy(day1), by2 = indexBy(day2);
      var out = [];
      PD.views.weekend.players.forEach(function (w) {
        var a = w.d1 ? by1[w.d1] : null;
        var b = w.d2 ? by2[w.d2] : null;
        if (!a && !b) return;
        var src = a || b;
        var row = { n: w.n, dn: w.dn, tm: src.tm, role: src.role, rs: src.rs,
                    ktpr: w.ktpr, tier: w.tier, arch: w.arch };
        SUM.forEach(function (k) {
          row[k] = ((a && a[k]) || 0) + ((b && b[k]) || 0);
        });
        // counts sum; the streak is a max, and its story travels with it
        var useA = !b || (a && (a.st || 0) >= (b.st || 0));
        row.st = useA ? (a ? a.st : 0) : b.st;
        row.sk = useA ? (a && a.sk) : b.sk;
        // rates recomputed from the summed totals — never averaged
        row.kd = row.d ? row.k / row.d : row.k;
        row.kph = row.h ? row.k / row.h : 0;
        row.fph = row.h ? row.fl / row.h : 0;
        row.prh = row.h ? row.pr / row.h : 0;
        // hitboxes were aggregated weekend-wide at source (both day rows carry
        // the same object); class spawns are per-day and merge here
        row.hb = (a && a.hb) || (b && b.hb) || {};
        row.cl = {};
        [a, b].forEach(function (s) {
          if (!s || !s.cl) return;
          Object.keys(s.cl).forEach(function (k) {
            row.cl[k] = (row.cl[k] || 0) + s.cl[k];
          });
        });
        out.push(row);
      });
      return out;
    }
    var MODELS = (function () {
      var d1 = dayModel(0, VIEW_KEYS[0]);
      var d2 = dayModel(1, VIEW_KEYS[1]);
      return [d1, d2, weekendModel(d1, d2)];
    })();
    var MAP_CACHE = {};
    function mapModel(vi, mp) {
      var ck = vi + "|" + mp;
      if (MAP_CACHE[ck]) return MAP_CACHE[ck];
      var key = VIEW_KEYS[vi];
      var rated = (PD.mapKtpr[key] || {})[mp] || {};
      var byName = indexBy(MODELS[vi]);
      var out = [];
      (LD.days[vi].maps[mp] || []).forEach(function (r) {
        if (rated[r.n] === undefined) return;
        var row = copyRow(r);
        row.ktpr = rated[r.n];
        var d = byName[r.n];   // style is the player's day style
        if (d) { row.tier = d.tier; row.arch = d.arch; }
        out.push(row);
      });
      MAP_CACHE[ck] = out;
      return out;
    }

    var elBaseline = document.getElementById("lb-baseline");
    var elRole = document.getElementById("lb-rolechips");
    var elTeam = document.getElementById("lb-teamchips");
    var elStyle = document.getElementById("lb-stylechips");
    var elMap = document.getElementById("lb-mapchips");
    var elMapHint = document.getElementById("lb-maphint");
    var elHead = document.getElementById("lb-head");
    var elShow = document.getElementById("lb-showall");
    var tabs = [document.getElementById("lb-tab-0"),
                document.getElementById("lb-tab-1"),
                document.getElementById("lb-tab-2")];

    function viewData() { return PD.views[VIEW_KEYS[state.view]]; }
    function isWeekend() { return state.view === 2; }
    function baseRows() {
      if (state.map !== null && !isWeekend()) return mapModel(state.view, state.map);
      return MODELS[state.view];
    }
    function filtered() {
      return baseRows().filter(function (r) {
        if (state.role !== null && r.role !== state.role) return false;
        if (state.team !== null && r.tm !== state.team) return false;
        if (state.arch !== null && r.arch !== state.arch) return false;
        return true;
      });
    }

    // ---- baseline strip ----
    function renderBaseline() {
      var v = viewData();
      var b = v.baseline;
      elBaseline.textContent = "";
      elBaseline.appendChild(el("span", "t", possessive(v.label) + " field baseline"));
      var s1 = el("span", null, "players ");
      s1.appendChild(el("b", null, String(b.pool)));
      elBaseline.appendChild(s1);
      var s2 = el("span", null, "regulars setting the medians ");
      s2.appendChild(el("b", null, String(b.regulars)));
      elBaseline.appendChild(s2);
      ROLE_ORDER.forEach(function (role) {
        var s = el("span", null, role + " ");
        s.appendChild(el("b", null, String(b.role_regulars[role] || 0)));
        elBaseline.appendChild(s);
      });
      elBaseline.appendChild(el("span", "hint",
        "KTPR measures every player below against the medians of these regulars \\u2014 " +
        "position by position, within this view only."));
    }

    // ---- filter chips ----
    function chip(label, pressed, onClick) {
      var b = el("button", "chip", label);
      b.setAttribute("aria-pressed", String(pressed));
      b.addEventListener("click", onClick);
      return b;
    }
    // Each chip row's counts respect the OTHER filters, so the numbers always
    // describe what clicking would actually show.
    function counts(skip) {
      var c = {};
      baseRows().forEach(function (r) {
        if (skip !== "role" && state.role !== null && r.role !== state.role) return;
        if (skip !== "team" && state.team !== null && r.tm !== state.team) return;
        if (skip !== "arch" && state.arch !== null && r.arch !== state.arch) return;
        var k = skip === "role" ? r.role : skip === "team" ? r.tm : r.arch;
        c[k] = (c[k] || 0) + 1;
      });
      return c;
    }
    function renderRoleChips() {
      elRole.textContent = "";
      var c = counts("role");
      elRole.appendChild(chip("All positions", state.role === null, function () {
        state.role = null; state.showAll = false; render();
      }));
      ROLE_ORDER.forEach(function (role) {
        elRole.appendChild(chip(role + " \\u00b7 " + (c[role] || 0), state.role === role, function () {
          state.role = state.role === role ? null : role; state.showAll = false; render();
        }));
      });
    }
    function renderTeamChips() {
      elTeam.textContent = "";
      var c = counts("team");
      elTeam.appendChild(chip("All teams", state.team === null, function () {
        state.team = null; state.showAll = false; render();
      }));
      TEAMS.forEach(function (t) {
        var b = chip(t[1] + " \\u00b7 " + (c[t[0]] || 0), state.team === t[0], function () {
          state.team = state.team === t[0] ? null : t[0]; state.showAll = false; render();
        });
        b.title = t[0];
        elTeam.appendChild(b);
      });
    }
    function renderStyleChips() {
      elStyle.textContent = "";
      var c = counts("arch");
      elStyle.appendChild(chip("All styles", state.arch === null, function () {
        state.arch = null; state.showAll = false; render();
      }));
      ARCH_ORDER.forEach(function (arch) {
        elStyle.appendChild(chip(arch + " \\u00b7 " + (c[arch] || 0), state.arch === arch, function () {
          state.arch = state.arch === arch ? null : arch; state.showAll = false; render();
        }));
      });
    }
    function renderMapChips() {
      elMap.textContent = "";
      if (isWeekend()) {
        // Disabled, not hidden: the control would otherwise appear to vanish.
        // Map splits are recorded per day; there is no cross-day aggregation.
        var union = [];
        LD.days.forEach(function (d) {
          Object.keys(d.maps || {}).forEach(function (m) {
            if (union.indexOf(m) === -1) union.push(m);
          });
        });
        var all = chip("All maps", true, function () {});
        all.disabled = true;
        elMap.appendChild(all);
        union.forEach(function (m) {
          var b = chip(m.replace(/^dod_/, ""), false, function () {});
          b.disabled = true;
          b.title = "Map boards are per-day \\u2014 pick Saturday or Sunday to see " +
                    m.replace(/^dod_/, "");
          elMap.appendChild(b);
        });
        elMapHint.hidden = false;
        return;
      }
      elMapHint.hidden = true;
      var maps = Object.keys(LD.days[state.view].maps || {});
      elMap.appendChild(chip("All maps", state.map === null, function () {
        state.map = null; state.showAll = false; render();
      }));
      maps.forEach(function (m) {
        elMap.appendChild(chip(m.replace(/^dod_/, ""), state.map === m, function () {
          state.map = state.map === m ? null : m; state.showAll = false; render();
        }));
      });
    }

    // ---- cells ----
    function rolePill(row) {
      var p = el("span", "rolepill" + (row.rs === "inferred" ? " inferred" : ""), row.role);
      p.title = row.rs === "inferred"
        ? "Position read from class play \\u2014 unchallenged in the staff pass"
        : "Position named by staff";
      return p;
    }
    function ktprCell(v, max) {
      var wrap = el("div", "ktprcell");
      wrap.appendChild(el("b", null, v.toFixed(3)));
      var bar = el("div", "ktprbar");
      var i = el("i");
      i.style.width = Math.max(4, Math.round(v / max * 100)) + "%";
      bar.appendChild(i);
      wrap.appendChild(bar);
      return wrap;
    }

    function detailRow(row, colspan) {
      var tr = el("tr", "detail");
      var td = el("td"); td.colSpan = colspan;
      var grid = el("div", "detailgrid");

      // hitboxes — hb entries are {hits, damage} objects (aggregated over the
      // whole weekend at source, on every view)
      var c1 = el("div");
      c1.appendChild(el("h4", null, "Where the hits landed"));
      var maxHits = 1;
      Object.keys(row.hb).forEach(function (k) { maxHits = Math.max(maxHits, row.hb[k].hits); });
      Object.keys(row.hb).forEach(function (k) {
        var r = el("div", "hbrow");
        r.appendChild(el("span", "lbl", k));
        var bar = el("div", "bar"); var i = el("i");
        i.style.width = Math.round(row.hb[k].hits / maxHits * 100) + "%";
        bar.appendChild(i); r.appendChild(bar);
        r.appendChild(el("span", "ct", row.hb[k].hits + " \\u00b7 " + fmt(row.hb[k].damage) + "dmg"));
        c1.appendChild(r);
      });
      grid.appendChild(c1);

      var c2 = el("div");
      c2.appendChild(el("h4", null, "Class spawns"));
      var dl2 = el("dl", "kvmini");
      Object.keys(row.cl).forEach(function (k) {
        dl2.appendChild(el("dt", null, k));
        dl2.appendChild(el("dd", null, fmt(row.cl[k])));
      });
      c2.appendChild(dl2);
      c2.appendChild(el("p", "hint mt8", "Position: " + row.role + " (" +
        (row.rs === "inferred" ? "read from class play" : "named by staff") + ")"));
      grid.appendChild(c2);

      var c3 = el("div");
      c3.appendChild(el("h4", null, "The rest of the ledger"));
      var dl3 = el("dl", "kvmini");
      [["Matches", row.m + " (" + row.h + " halves)"],
       ["Kills/half", row.kph.toFixed(1)], ["Flags/half", row.fph.toFixed(2)],
       ["Headshot kills", row.hs],
       ["Hits landed (HUD)", fmt(row.hits)], ["Headshot hits (HUD)", row.hsh],
       ["Flag caps (HUD)", row.caps], ["Objective score (HUD)", row.obj],
       ["Grenade kills (HUD)", row.nk], ["Gun kills (HUD)", row.gk],
       ["Time prone (HUD)", mmss(row.pr)],
       ["Times went prone (HUD)", row.pre === undefined ? "\\u2014" : row.pre],
       ["Average prone (HUD)", row.pre ? (row.pr / row.pre).toFixed(1) + "s" : "\\u2014"]
      ].forEach(function (p) {
        dl3.appendChild(el("dt", null, p[0]));
        dl3.appendChild(el("dd", null, String(p[1])));
      });
      // the best streak, told as the run it was; on the weekend view it is the
      // better of the two days' runs, and the story travels with the count
      if (row.sk) {
        var sk = row.sk;
        var sw = el("div", "streakbox");
        sw.appendChild(el("h4", null, "Longest streak"));
        var line = el("p", "sline");
        line.appendChild(el("b", null, row.st + " kills"));
        if (sk.vs) line.appendChild(document.createTextNode(" against " + sk.vs));
        var whenBits = [];
        if (sk.map) whenBits.push(sk.map);
        if (sk.day) whenBits.push(sk.day);
        if (sk.half) whenBits.push("half " + sk.half);
        if (whenBits.length) line.appendChild(el("span", "swhen", whenBits.join(" \\u00b7 ")));
        sw.appendChild(line);
        if (sk.guns && sk.guns.length) {
          var gl = el("p", "sguns");
          gl.appendChild(document.createTextNode(sk.guns.join(" \\u00b7 ")));
          sw.appendChild(gl);
        }
        c3.appendChild(sw);
      }
      c3.appendChild(dl3);
      grid.appendChild(c3);

      td.appendChild(grid);
      tr.appendChild(td);
      return tr;
    }

    // ---- column model ----
    // Uniform across the three views, so the grid never reshapes on a view
    // switch. A map sub-filter still drops Streak/Breaks/detail — the per-map
    // data never carried them (same behaviour the old day boards had).
    function columns(isMap) {
      var cols = [
        { key: "rank",   label: "#",       type: "rank" },
        { key: "player", label: "Player",  type: "alpha" },
        { key: "role",   label: "Pos",     type: "role" },
        { key: "ktpr",   label: "KTPR",    type: "num", tip: true },
        { key: "style",  label: "Style",   type: "style", stip: true },
        { key: "kd",     label: "K/D",     type: "num" },
        { key: "k",      label: "Kills",   type: "num" },
        { key: "d",      label: "Deaths",  type: "num" },
        { key: "fl",     label: "Flags",   type: "num" },
        { key: "hs",     label: "HS",      type: "num",
          hint: "headshot kills, and their share of that player's kills" },
        { key: "as",     label: "Assists", type: "num", hud: true },
        { key: "dm",     label: "Damage",  type: "num" }
      ];
      if (!isMap) {
        cols.push({ key: "st", label: "Streak", type: "num",
                    hint: "longest run of kills without dying, from the match record" },
                  { key: "cb", label: "Breaks", type: "num", hud: true,
                    hint: "enemy captures broken up" });
      }
      cols.push({ key: "pr", label: "Prone", type: "num", hud: true,
                  hint: "total time spent on the deck, m:ss \\u2014 each go-prone timed "
                      + "until the player stood up or died" });
      if (!isMap) cols.push({ key: "detail", label: "", type: null });
      return cols;
    }

    // ---- sorting model ----
    function byNumDesc(key) {
      return function (a, b) {
        var av = a[key] === undefined ? -Infinity : a[key];
        var bv = b[key] === undefined ? -Infinity : b[key];
        if (bv !== av) return bv - av;
        if (b.ktpr !== a.ktpr) return b.ktpr - a.ktpr;
        return a.n.localeCompare(b.n);
      };
    }
    function styleOrd(r) {
      return TIER_ORDER.indexOf(r.tier) * 10 + ARCH_ORDER.indexOf(r.arch);
    }
    // standings under the current ranking metric, independent of display order —
    // reversing a sort must not move the medals
    function standings(rows) {
      var order = rows.slice().sort(byNumDesc(state.rankKey));
      var pos = new Map();
      order.forEach(function (r, i) { pos.set(r, i); });
      return pos;
    }
    function sortRows(rows) {
      var out = rows.slice();
      var key = state.sortKey;
      if (key === "player") {
        out.sort(function (a, b) { return shortName(a.n).localeCompare(shortName(b.n)); });
      } else if (key === "role") {
        out.sort(function (a, b) {
          var d = ROLE_ORDER.indexOf(a.role) - ROLE_ORDER.indexOf(b.role);
          return d !== 0 ? d : b.ktpr - a.ktpr;
        });
      } else if (key === "style") {
        out.sort(function (a, b) {
          var d = styleOrd(a) - styleOrd(b);
          return d !== 0 ? d : b.ktpr - a.ktpr;
        });
      } else if (key === "rank") {
        out.sort(byNumDesc(state.rankKey));
      } else {
        out.sort(byNumDesc(key));
      }
      var canonicalIsAsc = (key === "player" || key === "role" ||
                            key === "style" || key === "rank");
      if (canonicalIsAsc ? state.sortDir === "desc" : state.sortDir === "asc") out.reverse();
      return out;
    }
    function clickSort(col) {
      var firstDir = { num: "desc", alpha: "asc", role: "asc", style: "asc", rank: "asc" };
      if (state.sortKey === col.key) {
        state.sortDir = state.sortDir === "desc" ? "asc" : "desc";
      } else {
        state.sortKey = col.key;
        state.sortDir = firstDir[col.type];
        if (col.type === "num") state.rankKey = col.key;
      }
      render();
    }

    // ---- tooltips (hover + keyboard focus on the column headers) ----
    function makeTip(id) {
      var t = el("div", "tooltip");
      t.id = id;
      t.setAttribute("role", "tooltip");
      t.hidden = true;
      document.body.appendChild(t);
      return t;
    }
    var ktprTip = makeTip("ktpr-tip");
    var styleTip = makeTip("style-tip");
    (function fillStyleTip() {
      var p1 = el("p"); p1.appendChild(el("b", null, "Style \\u2014 a tier and an archetype."));
      styleTip.appendChild(p1);
      styleTip.appendChild(el("p", null,
        "The tier is where the player's KTPR ranks within the current view: Ace is " +
        "the top 15%, Veteran to 40%, Regular to 70%, Recruit the rest."));
      styleTip.appendChild(el("p", null,
        "The archetype is the shape of the profile, not its quality \\u2014 three axes, " +
        "each measured against the view's field median: fragging (half K/D, half kills), " +
        "objective (70% flags, 30% capture breaks), support (60% assists, 40% damage)."));
      styleTip.appendChild(el("p", null,
        "Strong on two or more axes (1.12\\u00d7 the median or better) makes an " +
        "All-rounder; no axis ahead of the next by at least 0.12 makes a " +
        "Generalist. A fragging-led profile is a Sharpshooter when K/D leads " +
        "kill volume by 0.30 or more, otherwise a Fragger; objective-led is a " +
        "Flagger, support-led is Support."));
    })();
    function fillKtprTip() {
      var v = viewData();
      ktprTip.textContent = "";
      var p1 = el("p"); p1.appendChild(el("b", null, "KTPR \\u2014 the board's rating, the current team formula."));
      ktprTip.appendChild(p1);
      ktprTip.appendChild(el("p", null,
        "Six contributions \\u2014 kill volume (diminishing returns), kill efficiency " +
        "(K/D), assists, damage, flags, capture breaks \\u2014 each divided by the " +
        "median for the player's own position, weighted and averaged, with a gentle " +
        "death adjustment. 1.00 is an average player for this view's field."));
      ktprTip.appendChild(el("p", null,
        possessive(v.label) + " baselines come from its own " + v.baseline.regulars +
        " regulars. Every view runs the same formula against a different field, so " +
        "numbers compare within a view \\u2014 not across views."));
      if (state.map !== null && !isWeekend()) {
        ktprTip.appendChild(el("p", null,
          "Map boards: rated against the day's baselines, with the breaks term " +
          "omitted (breaks aren't recorded per map) and the remaining five " +
          "weights renormalized."));
      }
    }
    function showTip(tip, anchor, fill) {
      if (fill) fill();
      tip.hidden = false;
      var r = anchor.getBoundingClientRect();
      var w = Math.min(360, window.innerWidth - 24);
      tip.style.maxWidth = w + "px";
      tip.style.left = Math.max(12, Math.min(r.left, window.innerWidth - w - 12)) + "px";
      var top = r.bottom + 8;
      if (top + tip.offsetHeight > window.innerHeight - 8) top = Math.max(8, r.top - tip.offsetHeight - 8);
      tip.style.top = top + "px";
    }
    function hideTips() { ktprTip.hidden = true; styleTip.hidden = true; }
    window.addEventListener("scroll", hideTips, true);
    document.addEventListener("keydown", function (e) { if (e.key === "Escape") hideTips(); });
    function bindTip(btn, tip, fill) {
      btn.setAttribute("aria-describedby", tip.id);
      btn.addEventListener("mouseenter", function () { showTip(tip, btn, fill); });
      btn.addEventListener("mouseleave", hideTips);
      btn.addEventListener("focus", function () { showTip(tip, btn, fill); });
      btn.addEventListener("blur", hideTips);
    }

    // ---- render ----
    function render() {
      tabs.forEach(function (t, i) { t.setAttribute("aria-pressed", String(i === state.view)); });
      renderBaseline();
      renderRoleChips();
      renderTeamChips();
      renderStyleChips();
      renderMapChips();
      hideTips();

      var isMap = state.map !== null && !isWeekend();
      var rows = filtered();
      var cols = columns(isMap);
      var colKeys = cols.map(function (c) { return c.key; });
      if (colKeys.indexOf(state.sortKey) === -1) { state.sortKey = "ktpr"; state.sortDir = "desc"; }
      if (colKeys.indexOf(state.rankKey) === -1) state.rankKey = "ktpr";

      var v = viewData();
      var isFiltered = isMap || state.role !== null || state.team !== null || state.arch !== null;
      elHead.textContent = isFiltered
        ? v.label + (isMap ? " \\u00b7 " + state.map : "") +
          (state.team !== null ? " \\u00b7 " + (TEAM_TAG[state.team] || state.team) : "") +
          (state.role !== null ? " \\u00b7 " + state.role : "") +
          (state.arch !== null ? " \\u00b7 " + state.arch : "") + " \\u2014 ranked within this view"
        : v.label + " leaderboard \\u2014 all tournament matches";

      elTable.textContent = "";
      var thead = el("thead");
      var htr = el("tr");
      cols.forEach(function (col) {
        var th = el("th", col.type === "num" ? "r" : null);
        if (!col.type) { htr.appendChild(th); return; }
        var btn = el("button", "sortbtn");
        btn.appendChild(el("span", (col.tip || col.stip) ? "tipcue" : null, col.label));
        if (col.hud) btn.appendChild(el("span", "srcbadge", "HUD"));
        if (state.sortKey === col.key) {
          th.setAttribute("aria-sort", state.sortDir === "desc" ? "descending" : "ascending");
          btn.appendChild(el("span", "dir", state.sortDir === "desc" ? "\\u25bc" : "\\u25b2"));
        }
        var what = { rank: "rank", alpha: "player name", role: "position", style: "style" }[col.type] || col.label;
        btn.title = "Sort by " + what + (col.hint ? " (" + col.hint + ")" : "");
        btn.addEventListener("click", function () { clickSort(col); });
        if (col.tip) bindTip(btn, ktprTip, fillKtprTip);
        if (col.stip) bindTip(btn, styleTip, null);
        th.appendChild(btn);
        htr.appendChild(th);
      });
      thead.appendChild(htr);
      elTable.appendChild(thead);

      var tbody = el("tbody");
      var colspan = cols.length;
      var pos = standings(rows);
      var sorted = sortRows(rows);
      var maxK = sorted.reduce(function (m, r) { return Math.max(m, r.ktpr); }, 0.001);
      var limit = state.showAll ? sorted.length : Math.min(20, sorted.length);

      if (!sorted.length) {
        var trE = el("tr");
        var tdE = el("td", null, "No players in this view.");
        tdE.colSpan = colspan;
        trE.appendChild(tdE);
        tbody.appendChild(trE);
      }

      sorted.slice(0, limit).forEach(function (row) {
        var st = pos.get(row);
        var medal = st === 0 ? "m1" : st === 1 ? "m2" : st === 2 ? "m3"
          : (st === 3 || st === 4) ? "m45" : null;
        var tr = el("tr", medal);
        tr.appendChild(el("td", "rank", String(st + 1)));
        var tdp = el("td", "player", shortName(row.n)); tdp.title = row.n;
        tr.appendChild(tdp);
        var tdr = el("td"); tdr.appendChild(rolePill(row)); tr.appendChild(tdr);
        var tdk = el("td"); tdk.appendChild(ktprCell(row.ktpr, maxK)); tr.appendChild(tdk);
        tr.appendChild(el("td", null, row.tier + " " + row.arch));
        tr.appendChild(el("td", "r", row.kd.toFixed(2)));
        tr.appendChild(el("td", "r", String(row.k)));
        tr.appendChild(el("td", "r", String(row.d)));
        tr.appendChild(el("td", "r", String(row.fl)));
        // count with its share of that player's kills — 40 headshots off 300
        // kills is a different player from 40 off 120
        var tdHs = el("td", "r");
        if (row.hs === undefined) {
          tdHs.textContent = "\\u2014";
        } else {
          tdHs.appendChild(document.createTextNode(String(row.hs)));
          if (row.k) {
            tdHs.appendChild(el("span", "pct", (row.hs / row.k * 100).toFixed(0) + "%"));
            tdHs.title = row.hs + " of " + row.k + " kills were headshots";
          }
        }
        tr.appendChild(tdHs);
        tr.appendChild(el("td", "r", String(row.as)));
        tr.appendChild(el("td", "r", fmt(row.dm)));
        if (!isMap) {
          tr.appendChild(el("td", "r", String(row.st)));
          tr.appendChild(el("td", "r", String(row.cb)));
        }
        var tdPr = el("td", "r", mmss(row.pr));
        if (row.pre) {
          tdPr.title = row.pre + " times prone, averaging "
            + (row.pr / row.pre).toFixed(1) + "s each"
            + (row.prh ? " \\u00b7 " + mmss(row.prh) + " per half" : "");
        }
        tr.appendChild(tdPr);
        if (!isMap) {
          var tdd = el("td", "r");
          var btn = el("button", "detailbtn", "detail");
          btn.setAttribute("aria-expanded", "false");
          btn.addEventListener("click", function () {
            var open = btn.getAttribute("aria-expanded") === "true";
            btn.setAttribute("aria-expanded", String(!open));
            if (open) {
              var next = tr.nextElementSibling;
              if (next && next.classList.contains("detail")) next.remove();
            } else {
              tr.parentNode.insertBefore(detailRow(row, colspan), tr.nextElementSibling);
            }
          });
          tdd.appendChild(btn);
          tr.appendChild(tdd);
        }
        tbody.appendChild(tr);
      });
      elTable.appendChild(tbody);

      elShow.hidden = sorted.length <= 20;
      elShow.textContent = state.showAll
        ? "Show top 20 only"
        : "Show all " + sorted.length + " players";
    }

    tabs.forEach(function (t, i) {
      t.addEventListener("click", function () {
        // view switch resets the map (map pools differ, and the weekend has
        // none) but keeps position/team/style and the sort — the reader is
        // usually comparing like against like
        state.view = i; state.map = null; state.showAll = false; render();
      });
    });
    elShow.addEventListener("click", function () { state.showAll = !state.showAll; render(); });

    render();
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();"""


def page_names(page: str) -> dict:
    """The settled display names, read from the page's #player-names block.

    build_ballots.py derives them (team-prefix strip + flair trim + one-off
    untag) and embeds the answer; reading it back here keeps this board on the
    same rule without a second implementation.
    """
    m = re.search(r'<script id="player-names" type="application/json">(.*?)</script>',
                  page, re.S)
    return json.loads(m.group(1)) if m else {}


def page_lan_data(page: str) -> dict:
    m = re.search(r'<script id="lan-data" type="application/json">(.*?)</script>',
                  page, re.S)
    if not m:
        sys.exit(f"#lan-data block not found in {PAGE}")
    return json.loads(m.group(1))


def verify_join(board: dict, lan_data: dict) -> None:
    """The renderer joins ratings to #lan-data BY NAME. Prove at injection time
    that the join is total, so a silent miss can never put a legacy number (or
    no number) on the page."""
    day_names = {}
    for i, key in enumerate(DAY_KEYS):
        day_names[key] = {p["n"] for p in lan_data["days"][i]["players"]}
        rated = {r["name"] for r in board["views"][key]["players"]}
        if rated != day_names[key]:
            sys.exit(f"{key}: rating/#lan-data name mismatch: "
                     f"only-rated={sorted(rated - day_names[key])!r} "
                     f"only-page={sorted(day_names[key] - rated)!r}")
        for mp, rows in lan_data["days"][i]["maps"].items():
            page_names_ = {p["n"] for p in rows}
            rated_names = set(board["map_ktpr"][key].get(mp, {}))
            if rated_names != page_names_:
                sys.exit(f"{key} {mp}: map rating/#lan-data mismatch: "
                         f"only-rated={sorted(rated_names - page_names_)!r} "
                         f"only-page={sorted(page_names_ - rated_names)!r}")
    for r in board["views"]["weekend"]["players"]:
        for key in DAY_KEYS:
            n = r["names_by_day"].get(key)
            if n is not None and n not in day_names[key]:
                sys.exit(f"weekend: {r['name']!r} claims {key} name {n!r} "
                         f"not present in #lan-data")


def payload(board: dict, names: dict) -> str:
    views = {}
    for key in DAY_KEYS:
        v = board["views"][key]
        players = {}
        for r in v["players"]:
            tier, arch = r["style"].split(" ", 1)
            players[r["name"]] = [r["ktpr"], tier, arch]
        views[key] = {"label": v["label"], "baseline": v["baseline"],
                      "players": players}
    v = board["views"]["weekend"]
    wk = []
    for r in v["players"]:
        tier, arch = r["style"].split(" ", 1)
        wk.append({"n": r["name"], "dn": names.get(r["name"], r["name"]),
                   "tm": r["team"],
                   "d1": r["names_by_day"].get(DAY_KEYS[0]),
                   "d2": r["names_by_day"].get(DAY_KEYS[1]),
                   "ktpr": r["ktpr"], "tier": tier, "arch": arch})
    views["weekend"] = {"label": v["label"], "baseline": v["baseline"],
                        "players": wk}
    data = {"teams": TEAMS, "views": views, "mapKtpr": board["map_ktpr"]}
    # "</" would end the script block early if a name ever carries it
    return json.dumps(data, ensure_ascii=False,
                      separators=(",", ":")).replace("</", "<\\/")


def render(board: dict, names: dict) -> str:
    k = board["knobs"]
    tabs = []
    for i, (key, face, sub) in enumerate(TABS):
        pressed = "true" if key == "weekend" else "false"
        tabs.append(
            f'      <button class="daytab" id="lb-tab-{i}" aria-pressed="{pressed}">\n'
            f'        <b>{face}</b>\n'
            f'        <span>{sub}</span>\n'
            f'      </button>')
    tabs_html = "\n".join(tabs)
    return f"""{START}
  <section id="stats" data-ed="philly-2026">
    <div class="sec-head"><h2>Player stats</h2>
      <span class="meta">HLStatsX + broadcast HUD &middot; tournament (.ktp) matches only &middot; one grid, three views</span></div>

    <div class="note-box">
      <b>One formula, three fields.</b> Saturday, Sunday and the full weekend are
      views of one board, and every view is scored by the formula KTPR actually
      uses now &mdash; six contributions (kill volume, kill efficiency, assists,
      damage, flags, capture breaks) weighted into one number, each measured
      against the median of the player&rsquo;s own position. <b>1.00 is an
      average player for the view you&rsquo;re looking at.</b> What changes when
      you switch views is only the field being measured against: Saturday is
      rated against Saturday&rsquo;s players, Sunday against Sunday&rsquo;s
      thinner playoff field, the weekend against combined weekend totals. Same
      formula everywhere, different baseline populations &mdash; so compare
      numbers within a view, not across views. The weekend view is not an
      average of the day views: its counts are the two days summed and its rates
      are recomputed from those totals.
    </div>

    <!-- Why 2026 has a stats board at all and 2025 doesn't. Worth stating on
         the page: the gap between the two editions is infrastructure, not
         effort, and both halves of it are other people's work. -->
    <div class="note-box">
      <b>None of this existed last year.</b> Switch to <b>Philly 2025</b> in the
      edition bar: same event, same people, and the stats there are a scoreboard
      transcribed by hand. The difference is two pieces of work built between the
      LANs. The <b>KTP stack</b> made it possible &mdash; a 1.3 server that can be
      instrumented at all, which is not something DoD came with. The
      <b>broadcast HUD</b>, written by <b>Cadaver</b>, is what actually watched
      the matches, and it produced everything the scoreboard never knew: assists,
      damage down to the hitbox, kill streaks, capture breaks, who spent the
      round on the deck. One made the recording possible; the other did the
      recording. Both are open source &mdash;
      <a href="https://github.com/afraznein">github.com/afraznein</a> and
      <a href="https://github.com/JimmyLockhart65616">github.com/JimmyLockhart65616</a>.
    </div>

    <div class="note-box">
      <b>Two sources, and they don't measure the same window.</b> Columns marked
      <span class="srcbadge">HUD</span> come from the broadcast HUD, which saved
      on a timer while the server was up rather than only during live play &mdash;
      so those figures <b>can include warmup</b>. Two of the six rating inputs are
      HUD-sourced &mdash; assists and capture breaks exist nowhere else &mdash;
      and they carry the badge below. The other four (kill volume, kill
      efficiency, damage, flags) come from the match record and count match time
      only. The fix is to teach the match record to log assists and breaks
      itself; until then the badge is the honest label.
    </div>

    <div class="note-box">
      <b>Team finish is deliberately not in here.</b> The live formula can multiply
      each player by where their company finished. That is switched off for this
      board &mdash; it would fold the result of the weekend into a number presented
      as individual performance, and the awards this feeds are judged per stage.
    </div>

    <details class="panel kt-about">
      <summary>About KTPR &mdash; an experiment, and how it is worked out</summary>
      <div class="body">
        <p><b>Philly LAN 2026 is running an experimental KTPR.</b> It leans on
        stats that only exist because the broadcast HUD was watching &mdash;
        assists, damage, capture breaks &mdash; and that is exactly why it is not
        the finished article for future seasons. Read it as a worked example of
        what KTP could rate players on, not a settled standard. It will keep
        being tweaked.</p>

        <p><b>What it is trying to do.</b> A scoreboard rewards whoever killed
        the most, and Day of Defeat is not that game. Someone breaks a capture
        and dies for it. Someone puts four hundred damage into a push a teammate
        finishes. Someone spends the half holding a flag nobody ends up
        contesting. Those players win matches and a kill count cannot see any of
        them. KTPR is an attempt to put a number on the rest of the game, and to
        weigh each part against what an average player <i>at the same
        position</i> did &mdash; so a sniper is judged against snipers rather
        than against the field.</p>

        <h4>Where it started</h4>
        <p>The original formula, and what the day boards on this page used until
        now. Three terms, each a ratio to the field average:</p>
        <span class="formula">KTPR = [ (K/D &divide; field avg K/D)
       + (kills per half &divide; field avg)
       + 0.25 &times; (flags per half &divide; field avg) ] &divide; 2.25</span>
        <p>It is honest about what it measures, and what it measures is fragging
        with a nod to flags. A player who never tops a kill count cannot rate
        well in it, however the match was actually won.</p>

        <h4>What this board uses</h4>
        <p>Six contributions instead of three, each normalised against the median
        of the player&rsquo;s own position, then blended. <b>1.00 is an average
        player.</b> Every number below is printed from the weights the engine
        actually ran:</p>
        <span class="formula"><span class="c">every stat becomes a ratio to the position median, then is clamped:</span>
  R = clamp( value &divide; position median, {k["ratio_floor"]}, {k["ratio_cap"]} )
  <span class="c">capture breaks get +{k["break_smooth_k"]} on both sides first &mdash; the median is
  near zero, so without it one extra break swamps everything else</span>

<span class="c">low kills lift the support terms, because they are saying something the
kill count missed:</span>
  kill term   = R(kills) ^ {k["kill_exp"]}
  damage term = R(damage)  &times; clamp( 1 + {k["dmg_interaction"]} &times; (1 &minus; R(kills)), {k["dmg_scale_min"]}, {k["dmg_scale_max"]} )
  assist term = R(assists) &times; clamp( 1 + {k["assist_interaction"]} &times; (1 &minus; R(kills)), {k["dmg_scale_min"]}, {k["dmg_scale_max"]} )

<span class="c">the blend &mdash; kill efficiency carries the most weight:</span>
  score = ( {k["tw_kill"]} &times; kill term   + {k["tw_kd"]} &times; R(K/D)   + {k["tw_assist"]} &times; assist term
          + {k["tw_damage"]} &times; damage term + {k["tw_flag"]} &times; R(flags) + {k["tw_break"]} &times; R(breaks) ) &divide; {k["tw_sum"]}

<span class="c">deaths normalise rather than punish, and dying while out-fragging the
field counts as pushing rather than failing:</span>
  deaths       = (deaths per half &divide; position median)
                 &divide; ( 1 + {k["death_kill_relief"]} &times; max(0, R(kills) &minus; 1) )
  death adjust = 1 &minus; clamp( {k["death_w"]} &times; (deaths &minus; 1), &minus;{k["team_death_up_cap"]}, +{k["death_cap"]} )

  KTPR = score &times; death adjust</span>

        <h4>What the LAN bought us</h4>
        <p>The weekend was the use case. Damage already reaches the match record
        and this board now reads it from there; <b>assists and capture breaks are
        the two the record does not log yet</b>, which is the only reason they
        still carry a HUD badge. The work to log them through HLStatsX is planned
        for <b>Season 10</b>, and that matters for more than tidiness: the match
        record is gated to live play, so stats that arrive through it drop warmup
        automatically the way kills and flags already do. The LAN is what proved
        the stats were worth having and showed exactly which ones are missing.</p>

        <p class="kt-thanks"><b>Thanks are owed.</b> To <b>Cadaver</b>, for the
        broadcast HUD &mdash; none of the stats beyond a scoreboard exist without
        it. To <b>Krod</b> and <b>Chi</b> for the work on KTPR itself, which is
        where the formula above came from. And to everyone else who has put time
        into KTP&rsquo;s stats over the years, named here or not &mdash; this is a
        long list and leaving anyone off it would be the wrong kind of accuracy.
        It is a group effort, and it shows.</p>
      </div>
    </details>

    <div class="daytabs three" role="group" aria-label="Choose a view">
{tabs_html}
    </div>

    <div class="baseline" id="lb-baseline"></div>

    <div class="filters">
      <div class="chipgroup" role="group" aria-label="Filter by position">
        <span class="chiplabel" aria-hidden="true">Position</span>
        <span class="chipslot" id="lb-rolechips"></span>
      </div>
      <div class="chipgroup" role="group" aria-label="Filter by team">
        <span class="chiplabel" aria-hidden="true">Team</span>
        <span class="chipslot" id="lb-teamchips"></span>
      </div>
      <div class="chipgroup" role="group" aria-label="Filter by style">
        <span class="chiplabel" aria-hidden="true">Style</span>
        <span class="chipslot" id="lb-stylechips"></span>
      </div>
      <div class="chipgroup" role="group" aria-label="Filter by map">
        <span class="chiplabel" aria-hidden="true">Map</span>
        <span class="chipslot" id="lb-mapchips"></span>
        <span class="chiphint" id="lb-maphint" hidden>per-day only &mdash; map
          splits aren't recorded across days, so pick Saturday or Sunday to use
          them</span>
      </div>
    </div>

    <div class="panel">
      <div class="head" id="lb-head">Leaderboard</div>
      <div class="body scrollbox">
        <table class="leader" id="lb-table"></table>
        <div class="showall"><button class="btn ghost" id="lb-showall" hidden></button></div>
      </div>
    </div>

    <p class="status-foot"><b>Positions</b> are the league's four &mdash; Rifle,
      Heavy, 3rd, Sniper &mdash; finalized with staff after the event (dashed pill =
      read from class play; solid = named by staff). Click any column header to
      sort; rank, and the medal colours with it, recompute within whatever view,
      filter and sort you're looking at. Hover <b>KTPR</b> or <b>Style</b> for what
      the numbers and labels mean. Click <b>detail</b> on any row for hitboxes,
      class spawns and the rest of the ledger. Clan tags are stripped for display
      &mdash; the full in-game name is on each player cell's title, and a player
      who re-tagged between days appears under the name they played that day.</p>
    <p class="status-foot"><b>Counting basis:</b> kills, deaths, K/D, flags, damage,
      headshot kills and the longest streak are from the match record &mdash; exact, and
      scoped to match time. The streak is rebuilt from the frag log rather than read off
      the HUD, which reported it short whenever a run was still going at its last save.
      Everything marked <span class="srcbadge">HUD</span> &mdash; assists, capture
      breaks, prone, and the HUD rows in the detail panel &mdash; comes from the
      broadcast HUD's periodic save, and is pulled in two directions: the save runs
      whenever the server is up, so <b>warmup and knife rounds can land in the
      total</b>, while its final write comes before a half ends, so the tail of each
      half is <b>missing</b> (worth <b>11&ndash;19%</b>, on every player alike). Treat
      HUD columns as close, not exact. On the weekend view, counts are the two days
      summed, the streak is the better day's run, and rates are recomputed from the
      summed totals.</p>
    <p class="status-foot"><b>Map boards</b> (a map chip on a day view) are rated
      against that day's baselines with the breaks term omitted &mdash; breaks aren't
      recorded per map &mdash; and the remaining five weights renormalized; they also
      drop the streak/breaks columns and the detail panel, which are day-level.
      <b>Weights</b> kill_exp {k["kill_exp"]} &middot; kills {k["tw_kill"]} &middot;
      K/D {k["tw_kd"]} &middot; assists {k["tw_assist"]} &middot;
      damage {k["tw_damage"]} &middot; flags {k["tw_flag"]} &middot;
      breaks {k["tw_break"]} &middot; break smoothing {k["break_smooth_k"]}.
      Generated from the published stats by <b>build_season_board.py</b>, so the
      board and the numbers behind it cannot disagree.</p>
    <script id="lanboard-data" type="application/json">{payload(board, names)}</script>
    <script>
{SCRIPT}
    </script>
  </section>
{END}
"""


def main() -> int:
    board = json.load(open(BOARD, encoding="utf-8"))
    page = open(PAGE, encoding="utf-8").read()
    names = page_names(page)
    verify_join(board, page_lan_data(page))
    section = render(board, names)

    if START in page:
        # lambda replacement: the section carries backslashes and "\\g"-like
        # text a plain re.sub replacement string would mangle
        new = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?",
                     lambda m: section, page, flags=re.S)
    else:
        if ANCHOR not in page:
            print(f"anchor not found in {PAGE}: {ANCHOR}")
            return 2
        new = page.replace(ANCHOR, section + "\n  " + ANCHOR, 1)

    if "--check" in sys.argv:
        if new != page:
            print("prototype.html stats board is STALE — re-run inject_season_board.py")
            return 1
        print("prototype.html stats board is current")
        return 0

    if new == page:
        print("no change")
        return 0
    with open(PAGE, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    n = len(board["views"]["weekend"]["players"])
    print(f"injected unified stats board ({n} players, 3 views) into {PAGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
