#!/usr/bin/env python3
"""Pre-tick the awards that were already published, so a republish does not blank them.

The live page bakes its cards from awards.json. Once the section becomes
API-driven, an award appears only if `lan_award_selections` says so — so without
this seed a deploy shows staff a full candidate board and the public nothing.

The mapping is old published slug -> new catalogue slug. It is written out
rather than inferred: the old slugs are editorial names ('sponge', 'tourist')
and nothing in them derives the stat they measured.

⛔ The four `vote` awards are deliberately absent. They are gated by
`lan_awards.is_open` with real ballots already cast, and that gate is separate
from this one.

    python seed_award_selections.py           # print the SQL
    python seed_award_selections.py --check   # verify every target slug exists
"""
from __future__ import annotations

import io
import json
import os
import sys

import award_catalog

HERE = os.path.dirname(os.path.abspath(__file__))
AWARDS = os.path.join(HERE, "awards.json")
EDITION = "philly-2026"

# Published slug -> catalogue slug. Weekend cards and the role panel first, then
# the single-match records, in the order the page prints them.
MAPPING = {
    "mvp-sat": "day1-ktpr-high",
    "mvp-sun": "day2-ktpr-high",
    "fragger": "weekend-kills-high",
    "flagger": "weekend-flags-high",
    "flags-rate": "weekend-flags-per-half-high",
    "kd": "weekend-kd-high",
    "breaks": "weekend-cap-breaks-high",
    "assists": "weekend-assists-high",
    "headshots": "weekend-headshots-high",
    "prone": "weekend-prone-seconds-high",
    "restraining": "weekend-nemesis-pair-high",
    "melee": "weekend-melee-kills-high",
    "positions": "weekend-positions",
    "helping-hand": "match-assists-high",
    "amazon": "match-nade-kills-high",
    "benedict": "match-teamkills-high",
    "dont-touch": "match-damage-taken-low",
    "hurt-me": "match-deaths-high",
    "tourist": "match-kd-high",
    "horizontal": "match-prone-seconds-high",
    "headhunter": "match-headshots-high",
    "sponge": "match-damage-taken-high",
    "one-man": "match-kills-high",
    "damage": "match-damage-dealt-high",
    "streak": "match-best-streak-high",
}

VOTE_GATED = {"rookies", "carry", "losing", "improved"}


def published_slugs():
    """What the live page actually shows, read from the file it renders."""
    a = json.load(io.open(AWARDS, encoding="utf-8"))
    found = {x["slug"] for sec in ("decided", "single_match") for x in a.get(sec, [])}
    if a.get("positions"):
        found.add("positions")
    return found


def check():
    """Both directions: nothing published is unmapped, nothing mapped is invented."""
    problems = []
    catalogue = {d["slug"] for d in award_catalog.iter_definitions()}
    catalogue.add("weekend-positions")  # built by the generator, not the catalogue
    catalogue.update({"day1-ktpr-high", "day2-ktpr-high"})  # day scope expands per day

    live = published_slugs()
    for slug in sorted(live - set(MAPPING) - VOTE_GATED):
        problems.append("published award %r has no mapping — it would go dark" % slug)
    for old, new in sorted(MAPPING.items()):
        if new not in catalogue:
            problems.append("%r maps to %r, which no award generates" % (old, new))
        if old not in live and old != "positions":
            problems.append("%r is mapped but is not on the published page" % old)
    for slug in sorted(VOTE_GATED & set(MAPPING)):
        problems.append("%r is vote-gated and must not be seeded here" % slug)
    return problems


def statements():
    yield "-- Pre-tick the previously published awards. Generated by seed_award_selections.py."
    yield "START TRANSACTION;"
    for old, new in MAPPING.items():
        yield ("INSERT INTO lan_award_selections (edition, award_slug, match_key, selected) "
               "VALUES ('%s', '%s', '', 1) "
               "ON DUPLICATE KEY UPDATE selected=1;  -- was '%s'" % (EDITION, new, old))
    yield "COMMIT;"


if __name__ == "__main__":
    problems = check()
    for line in problems:
        print("FAIL " + line, file=sys.stderr)
    if "--check" in sys.argv:
        print("checked %d mappings" % len(MAPPING))
        sys.exit(1 if problems else 0)
    if problems:
        sys.exit(1)
    print("\n".join(statements()))
