#!/usr/bin/env python3
"""Fetch a KTP-ReHLDS CI engine build so Lane B can boot against a candidate.

`engine_i486.so` is baked into the runtime base image, so every Lane B run
otherwise measures a fixed engine -- and the engine is the one fleet artifact
the nightly swap keeps no rollback for. KTP-ReHLDS CI already builds and
verifies one; this pulls that exact build.

There is no fallback to the baked engine, deliberately. Falling back would run
a green Lane B against an engine that was never under test, and nothing in the
result would say so.

Retention on the source artifact is short and `.so` is not byte-reproducible
(build-id + __DATE__), so an expired artifact is a distinct, terminal outcome:
it cannot be regenerated by rebuilding the same commit.

    python scripts/fetch_engine_artifact.py --ref main --out build/engine

Exit codes are distinct so a caller can tell the failures apart:
  2 ref did not resolve      3 no artifact for that commit
  4 artifact expired         5 credential rejected
  6 artifact payload is not the engine
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import sys
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

EXIT_NO_REF = 2
EXIT_NO_ARTIFACT = 3
EXIT_EXPIRED = 4
EXIT_AUTH = 5
EXIT_PAYLOAD = 6

ELF32_MAGIC = b"\x7fELF\x01"

# Named rather than derived from the response: the download endpoint answers
# 401/403 for "wrong token" and for "token has no actions:read on that repo",
# and the two read identically without saying which scope is missing.
CREDENTIAL_HELP = (
    "The artifact download endpoint requires an authenticated token carrying "
    "actions:read on the source repository. Listing artifacts on a public repo "
    "does not; downloading one does. A workflow's default GITHUB_TOKEN is "
    "scoped to its own repository, so it is not sufficient across repos."
)


class _StripAuthOnHostChange(urllib.request.HTTPRedirectHandler):
    """Artifact downloads redirect to signed blob storage, which rejects the
    GitHub Authorization header -- and the resulting 403 reads as a bad token."""

    def redirect_request(self, req, fp, code, msg, headers, newurl):
        redirected = super().redirect_request(req, fp, code, msg, headers, newurl)
        if redirected is not None and redirected.host != req.host:
            redirected.remove_header("Authorization")
        return redirected


class Http:
    """The only thing that touches the network, so tests can replace it."""

    def __init__(self, token: str | None, api: str) -> None:
        self._token = token
        self.api = api.rstrip("/")
        self._opener = urllib.request.build_opener(_StripAuthOnHostChange())

    def _open(self, url: str):
        request = urllib.request.Request(url)
        request.add_header("Accept", "application/vnd.github+json")
        request.add_header("X-GitHub-Api-Version", "2022-11-28")
        if self._token:
            request.add_header("Authorization", f"Bearer {self._token}")
        return self._opener.open(request, timeout=60)

    def get_json(self, path: str) -> tuple[int, object]:
        try:
            with self._open(f"{self.api}{path}") as response:
                return response.status, json.load(response)
        except urllib.error.HTTPError as err:
            return err.code, None

    def get_bytes(self, path: str) -> tuple[int, bytes]:
        try:
            with self._open(f"{self.api}{path}") as response:
                return response.status, response.read()
        except urllib.error.HTTPError as err:
            return err.code, b""


class Failure(SystemExit):
    def __init__(self, code: int, message: str) -> None:
        super().__init__(code)
        self.message = message


def resolve_commit(http: Http, repo: str, ref: str) -> str:
    status, body = http.get_json(f"/repos/{repo}/commits/{ref}")
    if status in (401, 403):
        raise Failure(EXIT_AUTH, f"{repo} rejected the token resolving {ref!r}. {CREDENTIAL_HELP}")
    if status != 200 or not isinstance(body, dict) or not body.get("sha"):
        raise Failure(EXIT_NO_REF, f"{repo} has no commit for ref {ref!r} (HTTP {status})")
    return str(body["sha"])


def select_artifact(http: Http, repo: str, name: str) -> dict:
    status, body = http.get_json(f"/repos/{repo}/actions/artifacts?name={name}&per_page=100")
    if status in (401, 403):
        raise Failure(EXIT_AUTH, f"{repo} rejected the token listing {name}. {CREDENTIAL_HELP}")
    if status != 200 or not isinstance(body, dict):
        raise Failure(EXIT_NO_ARTIFACT, f"could not list artifacts on {repo} (HTTP {status})")

    candidates = [a for a in body.get("artifacts", []) if a.get("name") == name]
    if not candidates:
        raise Failure(
            EXIT_NO_ARTIFACT,
            f"{repo} published no artifact named {name}. That commit's CI either "
            "did not run, did not reach the upload step, or predates it.",
        )

    live = [a for a in candidates if not a.get("expired")]
    if not live:
        expiry = ", ".join(str(a.get("expires_at")) for a in candidates)
        raise Failure(
            EXIT_EXPIRED,
            f"every {name} on {repo} has expired ({expiry}). The engine is not "
            "byte-reproducible, so rebuilding that commit does not recreate it -- "
            "re-run the source CI to publish a fresh artifact.",
        )
    return max(live, key=lambda a: a.get("id", 0))


def extract_member(payload: bytes, member: str) -> bytes:
    try:
        archive = zipfile.ZipFile(io.BytesIO(payload))
    except zipfile.BadZipFile as err:
        raise Failure(EXIT_PAYLOAD, f"artifact download is not a zip: {err}") from err
    try:
        blob = archive.read(member)
    except KeyError:
        listing = ", ".join(archive.namelist()) or "<empty>"
        raise Failure(EXIT_PAYLOAD, f"artifact holds no {member}; it holds: {listing}") from None
    if not blob.startswith(ELF32_MAGIC):
        raise Failure(EXIT_PAYLOAD, f"{member} is not a 32-bit ELF; the engine must be i386")
    return blob


def fetch(http: Http, *, repo: str, ref: str, prefix: str, member: str,
          out_dir: Path) -> dict:
    commit = resolve_commit(http, repo, ref)
    name = f"{prefix}{commit}"
    artifact = select_artifact(http, repo, name)

    status, payload = http.get_bytes(
        f"/repos/{repo}/actions/artifacts/{artifact['id']}/zip")
    if status in (401, 403):
        raise Failure(EXIT_AUTH, f"{repo} refused the {name} download. {CREDENTIAL_HELP}")
    if status != 200:
        raise Failure(EXIT_NO_ARTIFACT, f"downloading {name} returned HTTP {status}")

    blob = extract_member(payload, member)
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / Path(member).name
    target.write_bytes(blob)
    target.chmod(0o755)

    return {
        "repository": repo,
        "requested_ref": ref,
        "commit": commit,
        "artifact_name": name,
        "artifact_id": artifact.get("id"),
        "expires_at": artifact.get("expires_at"),
        "workflow_run_id": (artifact.get("workflow_run") or {}).get("id"),
        "member": member,
        "path": str(target),
        "bytes": len(blob),
        "sha256": hashlib.sha256(blob).hexdigest(),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default="afraznein/KTP-ReHLDS")
    ap.add_argument("--ref", required=True, help="branch, tag or commit in --repo")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--name-prefix", default="rehlds-engine-")
    ap.add_argument("--member", default="engine_i486.so")
    ap.add_argument("--provenance", type=Path)
    ap.add_argument("--api", default="https://api.github.com")
    ap.add_argument("--token-env", default="GH_TOKEN",
                    help="environment variable holding the token; never a literal")
    args = ap.parse_args(argv)

    http = Http(os.environ.get(args.token_env) or None, args.api)
    try:
        provenance = fetch(http, repo=args.repo, ref=args.ref,
                           prefix=args.name_prefix, member=args.member,
                           out_dir=args.out)
    except Failure as failure:
        print(f"::error::{failure.message}", file=sys.stderr)
        return int(failure.code)

    if args.provenance:
        args.provenance.parent.mkdir(parents=True, exist_ok=True)
        args.provenance.write_text(json.dumps(provenance, indent=2) + "\n")
    print(json.dumps(provenance, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
